name: CD-pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: rm -rf ./*

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup Old Containers
        working-directory: ./deployment
        run: docker compose -f compose.prod.yaml down

      - name: Create .env file
        working-directory: ./deployment
        run: |
          echo "${{ secrets.ENV }}" > .env.prod

      - name: Check Docker
        run: |
          docker info
          docker compose

      - name: Deploy with Docker Compose
        working-directory: ./deployment
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker compose -f compose.prod.yaml --env-file .env.prod up -d --build

      - name: Cleanup docker
        run: |
          docker system prune -f
